baseURL = 'https://endjetlagbook.com/'
languageCode = 'en-au'
title = 'End Jet Lag'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]

DefaultContentLanguage = "en"
contentDir = "content/en"
SectionPagesMenu = "main"
pagination.pagerSize = 9
# googleAnalytics = ""
enableRobotsTXT = false
enableEmoji = true
cleanDestinationDir = true
copyright = "Dr Steve Jasper"
enableGitInfo = true

[languages]
[languages.en]
title = "End Jet Lag"
contentDir = "content/en"

[sitemap]
changefreq = "weekly"
priority = 0.5
filename = "sitemap.xml"

[fonts]
use_google_fonts = true
google_fonts_url = "https://fonts.googleapis.com/css2?family=Overpass+Mono:wght@300..700&family=Overpass:ital,wght@0,100..900;1,100..900&display=swap"
use_self_hosted_fonts = false
logo = "Overpass"
heading = "Overpass"
base = "Overpass"
monospace = "Overpass Mono"

[params]
author = "Dr Steve Jasper"
description = "End Jet Lag"
favicon = "/images/blueclock.png"
site_logo = "/images/logo.png"
date_format = ":date_full"
custom_css = ["tjlg.scss"]
omit_header_text = true
text_color = "charcoal"                 # "charcoal", or "dark-gray"
recent_posts_number = 3
background_color_class = "bg-maroon"
body_classes = "overpass bg-near-white"
post_content_classes = "overpass"

[ananke.social.share]
icons = true
sharetext = true
networks = ["email", "facebook", "twitter", "linkedin"]

[ananke.social.follow]
new_window_icon = false
networks = ["email", "linkedin", "youtube", "facebook", "twitter", "rss"]

# [[params.ananke_socials]]
# name = "e-mail"
# url = "mailto:drsteve@jetlagguy.com.au"
[[ananke.social.email]]
profilelink = "mailto:drsteve@jetlagguy.com.au"

# [[params.ananke_socials]]
# name = "linkedin"
# url = "https://www.linkedin.com/in/jasperstephen/"z
[[ananke.social.linkedin]]
username = 'jasperstephen'
# profilelink = 'https://linkedin.com/in/jasperstephen/'

# [[params.ananke_socials]]
# name = "youtube"
# url = "https://www.youtube.com/@TheJetLagGuy"
[[ananke.social.youtube]]
profilelink = "https://www.youtube.com/@TheJetLagGuy"

# [[params.ananke_socials]]
# name = "facebook"
# url = "https://www.facebook.com/steve.jasper.965/"
[[ananke.social.facebook]]
profilelink = "https://www.facebook.com/steve.jasper.965/"

# [[params.ananke_socials]]
# name = "twitter"
# url = "https://twitter.com/DrSteveJasper/"
[[ananke.social.twitter]]
username = "DrSteveJasper"
# profilelink = "https://twitter.com/DrSteveJasper/"

# [[params.ananke_socials]]
# name = "X"
# url = "https://x.com/DrSteveJasper/"

# tiktok?

# instagram?

[[ananke.social.rss]]
title = "rss"
profilelink = "/index.xml"
